#!/usr/bin/env python3
"""Generate the embedded Lean witness table from the canonical CSV."""

from __future__ import annotations

import argparse
import csv
import pathlib


def data_lines(filename: pathlib.Path):
    with filename.open("r", encoding="utf-8", newline="") as handle:
        yield from (line for line in handle if line.strip() and not line.startswith("#"))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    args = parser.parse_args()

    rows = list(csv.DictReader(data_lines(args.source)))
    if len(rows) != 593:
        raise SystemExit(f"refusing to generate: expected 593 rows, got {len(rows)}")

    entries = []
    for row in rows:
        entries.append(f"  {{ n := {row['n']}, j := {row['j']}, q := {row['q']} }}")

    body = """import Collatz.Segment

/-! This file is generated by `scripts/generate_published_lean.py`. -/

namespace Collatz.Certified

structure PublishedWitness where
  n : ℕ
  j : ℕ
  q : ℕ
deriving DecidableEq, Repr

def publishedWitnesses : List PublishedWitness := [
""" + ",\n".join(entries) + """
]

def checkPublishedWitness (w : PublishedWitness) : Bool :=
  decide (oddCount w.n w.j = w.q ∧ Paradoxical w.n w.j)

theorem published_count : publishedWitnesses.length = 593 := by native_decide

theorem published_pairs_nodup :
    (publishedWitnesses.map fun w => (w.n, w.j)).Nodup := by native_decide

theorem published_distinct_starts :
    (publishedWitnesses.map (fun w => w.n)).eraseDups.length = 550 := by native_decide

theorem published_max_start :
    publishedWitnesses.all (fun w => decide (w.n ≤ 4614)) = true := by native_decide

theorem published_group_counts :
    (publishedWitnesses.filter (fun w => decide (w.j = 8 ∧ w.q = 5))).length = 5 ∧
    (publishedWitnesses.filter (fun w => decide (w.j = 27 ∧ w.q = 17))).length = 50 ∧
    (publishedWitnesses.filter (fun w => decide (w.j = 46 ∧ w.q = 29))).length = 231 ∧
    (publishedWitnesses.filter (fun w => decide (w.j = 54 ∧ w.q = 34))).length = 2 ∧
    (publishedWitnesses.filter (fun w => decide (w.j = 65 ∧ w.q = 41))).length = 244 ∧
    (publishedWitnesses.filter (fun w => decide (w.j = 73 ∧ w.q = 46))).length = 56 ∧
    (publishedWitnesses.filter (fun w => decide (w.j = 92 ∧ w.q = 58))).length = 5 := by
  native_decide

theorem every_published_witness_checks :
    publishedWitnesses.all checkPublishedWitness = true := by native_decide

end Collatz.Certified
"""
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(body, encoding="utf-8", newline="\n")
    print(f"generated {args.output} with {len(rows)} embedded witnesses")


if __name__ == "__main__":
    main()

